### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by NilsScriptDE** [GianC-Dev/NitroGen#1]
How do I have to use start.bat? for me the terminal belongs but it belongs again without no messages

**Comment by GianC-Dev** [comment]
open the glitch.com then register to website. click new project button then click the clone from git repo put the this repo link. and enter the discord developers. if not logined once register after login in. click new application then click bot and click new bot. copy there token. and enter the glitch project. then paste this token to code.

**Comment by GianC-Dev** [comment]
for windows: enter the discord developers. if not logined once register after login in. click new application then click bot and click new bot. copy there token. and enter the code with notepad. then paste this token to code.

**Comment by itsdrharsh** [comment]
> 
> 
> open the glitch.com then register to website. click new project button then click the clone from git repo put the this repo link. and enter the discord developers. if not logined once register after login in. click new application then click bot and click new bot. copy there token. and enter the glitch project. then paste this token to code.

plz repeat not understood
